### ISSUE TITLE
Support providing multiple OTEL_RESOURCE_ATTRIBUTES environment variables

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-specification#2135]
**What are you trying to achieve?**

I want to set resource attributes from multiple env variables. This is especially useful in Kubernetes with the downward API to set resource attribute for node, pod, namespace name etc.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      env:
        - name: OTEL_RESOURCE_ATTRIBUTES_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OTEL_RESOURCE_ATTRIBUTES_K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES_K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_ATTRIBUTES_K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES_K8S_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
```

The implementation(SDK) could get all env vars starting with `OTEL_RESOURCE_ATTRIBUTES_` and add them to resource attributes. The key of the attribute would be everything after  `OTEL_RESOURCE_ATTRIBUTES_`, the `_` substituted by `.` and all characters would be made lower case. 

Current spec: https://github.com/open-telemetry/opentelemetry-specification/blob/48ea76ccf06a027278e885e774b1371b91d6454d/specification/sdk-environment-variables.md
K8s resource attributes: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md

**Comment by pavolloffay** [comment]
The following pod spec shows how this can be achieved 

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
  name: backend2-deployment-58cfcb8db7-tdc8v
  namespace: tutorial-application
spec:
  containers:
  - env:
    - name: JAVA_TOOL_OPTIONS
      value: ' -javaagent:/otel-auto-instrumentation/javaagent.jar'
    - name: OTEL_SERVICE_NAME
      value: backend2-deployment
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector.observability-backend.svc.cluster.local:4317
    - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage,b3
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "1"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.container.name=backend2,k8s.deployment.name=backend2-deployment,k8s.namespace.name=tutorial-application,k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.replicaset.name=backend2-deployment-58cfcb8db7
```
