### ISSUE TITLE
Metrics Semantic Conventions not specified as YAML files

### ISSUE THREAD

**Issue by FWinkler79** [open-telemetry/opentelemetry-specification#2666]
**What are you trying to achieve?**

I looked at the semantic conventions described in YAML and used as a basis for generating markdown.
YAML files exist for `resources` and `trace spans` but they don't seem to exist for `metrics`.
However, there is a semantic convention described for metrics already [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md) which reference sub pages that list metrics-related attributes for e.g. [HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md), [Database](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/database-metrics.md), etc.

None of these pages seem to contain attribute tables generated from YAML. Is that just temporary or is there a deeper reason why metrics are not yet specified in YAML?

**Update:** The same is apparently happening for [log attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/semantic_conventions/media.md)

**What did you expect to see?**

Have metrics-related attributes and their semantics defined in YAML and referenced in markdown (as generated tables) instead of simply describing them in markdown manually.

**Additional context.**

none

**Comment by jsuereth** [comment]
@Oberon00 I think you mean: https://github.com/open-telemetry/build-tools/pull/79

Regarding both metrics + logs semantic conventions, the build tooling to generate from markdown was not built / ingested yet.

**Comment by FWinkler79** [comment]
Thanks, I interpret this as "There is a more up-to-date toolchain required to make this possible". Am I correct in that assumption?

Btw.: I gave it a try to reverse-engineer the metrics [http-attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md) markdown into yaml.
The below code generates something very close to the original markdown. Maybe someone could have a look at this, if this goes in the right direction.

```yaml
groups:
  - id: http.metrics
    extends: http
    prefix: http
    brief: 'This document defines semantic conventions for HTTP client and server metrics attributes.'
    attributes:
      - ref: http.method
        requirement_level: required
      - ref: http.host
      - ref: http.scheme
      - ref: http.status_code
      - ref: http.flavor
      - ref: net.sock.peer.addr
        requirement_level: 
          conditionally_required: For clients only.
      - ref: net.sock.peer.port
        requirement_level: 
            conditionally_required: For clients only.
      - ref: net.sock.peer.name
        requirement_level: 
          conditionally_required: For clients only.
      - ref: net.host.name
        requirement_level: 
          conditionally_required: For servers only.
      - ref: net.host.port
        requirement_level: 
          conditionally_required: For servers only.
      - ref: http.server_name
        requirement_level: 
          conditionally_required: For servers only.
  
  - id: http.client.metrics
    extends: http.metrics
    prefix: http.client
    brief: 'Semantic Convention for HTTP Client metrics attributes'
    attributes:
      - id: duration
        type: int
        brief: >
          measures the duration outbound HTTP requests. Unit: milliseconds, ms
        examples: 300
    constraints:
      - any_of:
          - [http.url]
          - [http.scheme, http.host, http.target]
          - [http.scheme, net.peer.name, net.peer.port, http.target]
          - [http.scheme, net.sock.peer.addr, net.sock.peer.port, http.target]
      
  - id: http.client.request.metrics
    extends: http.client.metrics
    prefix: http.client.request
    brief: 'Semantic Convention for HTTP Client request metrics attributes'
    attributes:
      - id: size
        type: int
        brief: >
          measures the size of HTTP request messages (compressed). Unit: bytes, by
        examples: 1024
      
  - id: http.client.response.metrics
    extends: http.client.metrics
    prefix: http.client.response
    brief: 'Semantic Convention for HTTP Client response metrics attributes'
    attributes:
      - id: size
        type: int
        brief: >
          measures the size of HTTP response messages (compressed). Unit: bytes, by
        examples: 1024
    
  - id: http.server.metrics
    extends: http.metrics
    prefix: http.server
    brief: 'Semantic Convention for HTTP Server metrics attributes'
    attributes:
      - id: duration
        type: int
        brief: >
          measures the duration inbound HTTP requests. Unit: milliseconds, ms
        examples: 300
      - id: active_requests
        type: int
        brief: >
          measures the number of concurrent HTTP requests that are currently in-flight. Unit: requests
        examples: 300
    constraints:
      - any_of:
          - [http.scheme, http.host, http.target]
          - [http.scheme, http.server_name, net.host.port, http.target]
          - [http.scheme, net.host.name, net.host.port, http.target]
          - [http.url]

  - id: http.server.request.metrics
    extends: http.server.metrics
    prefix: http.server.request
    brief: 'Semantic Convention for HTTP Server request metrics attributes'
    attributes:
      - id: size
        type: int
        brief: >
          measures the size of HTTP request messages (compressed). Unit: bytes, by
        examples: 1024
  
  - id: http.server.response.metrics
    extends: http.server.metrics
    prefix: http.server.response
    brief: 'Semantic Convention for HTTP Server response metrics attributes'
    attributes:
      - id: size
        type: int
        brief: >
          measures the size of HTTP response messages (compressed). Unit: bytes, by
        examples: 1024
```
