### ISSUE TITLE
Verify resource attributes rename in schemas is correct

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#3245]
As shown by #3190, using the `spans` format to rename attributes doesn't work for `resources` - instead, the following is needed. Whether that's fine or it's a limitation, we need to make it clear (i.e. see the `attribute_map` omission). 

```yaml
    spans:
      changes:
        - rename_attributes:
            attribute_map:
              http.user_agent: user_agent.original
```

```yaml
    resources:
      changes:
        - rename_attributes:
          browser.user_agent: user_agent.original
```

Wdyt @tigrannajaryan ?
