### ISSUE TITLE
`http.route` convention: broaden definition

### ISSUE THREAD

**Issue by howardjohn** [open-telemetry/opentelemetry-specification#3517]
**What are you trying to achieve?**

In https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md,  http.route is defined as:

The matched route (path template in the format used by the respective server framework)  `/users/:userID?; {controller}/{action}/{id?}`

In our API, we have named route matches, which have attributes beyond just path. For example:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - name: "reviews-consumer"
    match:
    - uri:
        prefix: "/consumercatalog"
       headers:
         end-user:
           exact: jason
```

Intuitively, I would expect `http.route=reviews-consumer` here. However, this doesn't directly align with the spec which specified _path template_.

Is this something that could be expanded to be in scope for `http.route`? Perhaps "The matched route (path template in the format used by the respective server framework, **or other route identifier**)"?
