### ISSUE TITLE
logs: Mechanism to preserve a log body while also parsing it

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-specification#3932]
It is often not possible to send the same log data to multiple backends. This seems undesirable and unnecessary. Ultimately, I propose a new field on the log data model. To illustrate the problem, here is a detailed example:

---

Suppose I have read the following log from a file called `foo.txt`: 
`[INFO] 8/3/24 12:34:56 { "message": "hello", "foo": { "bar": "baz" } }`

Prior to any processing, I have the following:

```yaml
Attributes:
  log.file.name: foo.txt
Body: [INFO] 8/3/24 12:34:56 { "message": "hello", "foo": { "bar": "baz" } }
```

At this point, I'd like to send this log to several different backends. However, each backend has different requirements which appear to be conflicting. Our data model is flexible enough to support _any one_ of these options, but it does not appear possible to support all of them at once. 

---

Backend 1 intends to perform all necessary parsing from scratch, so it needs the entire original log with no modifications whatsoever. Optionally, a `log.type` attribute can indicate which parsing algorithm to apply, so perhaps we add an attribute.

```yaml
Attributes:
  log.file.name: foo.txt
  log.type: foo
Body: [INFO] 8/3/24 12:34:56 { "message": "hello", "foo": { "bar": "baz" } }
```

---

Backend 2 needs the body to be a string, but it won't perform any parsing. Therefore, we need to extract the timestamp and severity prior to sending. Optionally, we could remove the corresponding portions of the string, but leaving them in place allows us to send this to Backend 1 as well.

```yaml
Attributes:
  log.file.name: foo.txt
  log.type: foo
Severity: INFO
Timestamp: 8/3/24 12:34:56
Body: [INFO] 8/3/24 12:34:56 { "message": "hello", "foo": { "bar": "baz" } }
```

So far so good. We've made no destructive modifications to the log and can send it to both Backends 1 and 2.

---

Backend 3 expects structured log bodies, so ideally we would parse the body and overwrite it.

```yaml
Attributes:
  log.file.name: foo.txt
Severity: INFO
Timestamp: 8/3/24 12:34:56
Body: 
  message: hello
  foo:
    bar: baz
```

This is no longer compatible with Backends 1 or 2.

Arguably, we could reformat this a bit to make it compatible with Backend 2. Specifically, we could consider the "message" to be the body, and flatten everything else into attributes. This kind of manipulation relies heavily on interpretation.

```yaml
attributes:
  log.file.name: foo.txt
  foo.bar: baz
severity: INFO
timestamp: 8/3/24 12:34:56
body: hello
```

Either way, it appears to be impossible to send the same data to both Backends 1 and 3, unless we first copy it and then process it separately, which should not be necessary.

---

I think we should formalize the notion of "original log body" in some way, so that the same log can be sent to all three backends. The alternative appears to be fragmentation and processing which is highly sensitive to specific needs of eventual consumers.

A semantic convention would potentially be enough here, but this need is so closely related to the basic mechanics of working with logs that I think a new field on the data model may be more appropriate. My attempt at defining this field would look like this:

```md
### OriginalBody (Optional)

A copy of the Log Record's original Body value.

If the field contains a value, it MUST be exactly the value which the Body first contained.

When this field contains a value, it SHOULD be assumed that the Body field was changed.

Likewise, when the field does not contain a value, it SHOULD be assumed that the Body field has NOT changed.
```

This field would allow both Backends 1 and 2 to implement some very simple logic to prefer OriginalBody over Body, thus allowing the log to be processed with much less sensitivity to the needs of eventual consumers. The example log could look like this:

```yaml
Attributes:
  log.file.name: foo.txt
  log.type: foo
Severity: INFO
Timestamp: 8/3/24 12:34:56
Body: 
  message: hello
  foo:
    bar: baz
OriginalBody: [INFO] 8/3/24 12:34:56 { "message": "hello", "foo": { "bar": "baz" } }
```

---

Related:
- https://github.com/open-telemetry/opentelemetry-specification/issues/3014
- https://github.com/open-telemetry/opentelemetry-specification/issues/2067
- https://github.com/open-telemetry/opentelemetry-specification/issues/2066
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16495#issuecomment-1690152673
- https://github.com/open-telemetry/opentelemetry-specification/pull/3827
