### ISSUE TITLE
[configuration] Force type when doing environment variable substitution

### ISSUE THREAD

**Issue by flyfire2002** [open-telemetry/opentelemetry-specification#4281]
**What are you trying to achieve?**

When substituting env variables like "00001" (as a string) (e.g. into an attribute), the type of the produced value is automatically Int. I want to be able to force it to type Str at substitution. Note, currently with `attribute: convert` it is done after the value is already substituted as an Int, so in this case it will be doing Int(1) => Str(1), which is still not the same as Str(00001).

** Context/Example **

With config
```
  resource/common_labels:
    attributes:
    - key: some_id
      value: "${id}"
      action: upsert
```

When the env var id = "00001", the value of the attribute "some_id" will be Int(1).
If we do a
```
    - key: some_id
      action: convert
      converted_type: string
```
afterwards, the value is Str(1) which is still different from "00001" / Str(00001).

**Comment by jack-berg** [comment]
Seems like this should be transferred to `opentelemetry-collector-contrib`.

**Comment by flyfire2002** [comment]
Filed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36183 though I feel like this is not a one-processor-specific problem.

**Comment by trask** [comment]
hi @flyfire2002, we don't think this is a spec issue since the spec doesn't say anything about collector processors

**Comment by Aneurysm9** [comment]
I think this is indeed a spec issue as the issue is not with collector processors but with how the collector configuration system handles environment variable substitution.  The [expressed intent](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/env-vars.md?plain=1#L170-L171) there is for the behavior to "support the exact same syntax as the Configuration WG."  Here collector processors were only used as the medium for conveying a description of the issue.

If the behavior the Configuration WG expects is for an environment variable containing `0001` to be cast as an integer `1` before any further processing can happen with no mechanism for signaling that it should instead be treated as a string then I think the specification is defective.  As an example, AWS account IDs are strings that match the regex `^[0-9]{12}$`.  That means `012345678912` is a valid AWS account ID that would be impossible to represent correctly in a configuration using environment variable substitution as it will be interpreted as the integer value `12345678912`.

**Comment by trask** [comment]
@open-telemetry/configuration-approvers can you review @Aneurysm9's https://github.com/open-telemetry/opentelemetry-specification/issues/4281#issuecomment-2603193985? thanks!

**Comment by jack-berg** [comment]
> with no mechanism for signaling that it should instead be treated as a string

There are two mechanisms for this. First, if you want to ensure that an ambiguous value like `0001` is interpreted as string `"0001"` instead of an integer `1`, you can put it in double quotes:

```
# input, with id=0001
key: "${id}" # yields string "0001"
```

You can see an example of this in the spec [here](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/configuration/data-model.md#L136).

Second, you can use YAML tags to coerce the parser to interpreting the value as a specific type:
```
key1: 1 # yields integer 1
key2: !!str 1 # yields string "1"
key3: !!str ${id} # yields "0001"
```

**Comment by Aneurysm9** [comment]
> There are two mechanisms for this. First, if you want to ensure that an ambiguous value like `0001` is interpreted as string `"0001"` instead of an integer `1`, you can put it in double quotes:
> 
> ```
> # input, with id=0001
> key: "${id}" # yields string "0001"
> ```
>
> You can see an example of this in the spec [here](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/configuration/data-model.md#L136).

This does not work.  Perhaps this is a defect in the collector's handling of substitutions.  I'm also not sure the linked example is illustrating this as I can't tell whether `"true"` is being coerced to the boolean `true` and then inserted into the exogenous quotes.  This would not have the expected results with an integer type as coercing it to an integer would make `0001` become `1`, which was the behavior we observed.  

To be more concrete, here's an example of a collector configuration chunk that has the issue:

```sh
ACCOUNT_ID=012345678912
```

```yaml
  attributes/add_labels:
    actions:
      - action: insert
        key: account_id
        value: ${env:ACCOUNT_ID} # evaluates to `12345678912`
```

Wrapping the substitution in quotes at this layer of processing has no effect as the input has already been cast as an integer.  IOW, this configuration produced the same result, namely a truncated account ID:

```yaml
  attributes/add_labels:
    actions:
      - action: insert
        key: account_id
        value: "${env:ACCOUNT_ID}" # evaluates to `12345678912`
```

Wrapping the value in the environment variable in quotes such that they were part of the value prevented integer conversion and truncation, but then resulted in undesired literal quotes in the attribute value:

```sh
ACCOUNT_ID="\"012345678912\""
```

```yaml
  attributes/add_labels:
    actions:
      - action: insert
        key: account_id
        value: ${env:ACCOUNT_ID} # evaluates to `"012345678912"`
```

Ultimately, in this particular situation we were able to work around the issue by reading the environment variable with the quotes into a temporary attribute, extracting the desired digits from that temporary attribute, and then deleting the temporary attribute.  This is obviously less than ideal and simply not an option in some situations.

```yaml
  attributes/add_labels:
    actions:
      - action: insert
        key: tmp_account_id
        value: ${env:ACCOUNT_ID}
      - action: extract
        key: tmp_account_id
        pattern: (?<account_id>\d{12})
      - action: delete
        key: tmp_account_id
```

> Second, you can use YAML tags to coerce the parser to interpret the value as a specific type:
> 
> ```
> key1: 1 # yields integer 1
> key2: !!str 1 # yields string "1"
> key3: !!str ${id} # yields "0001"
> ```

Perhaps this is a collector defect, but I tried this:

```sh
ACCOUNT_ID="!!str 012345678912"
```

and the injected attribute value was `!!str 012345678912` and not `012345678912` as expected.  This seems to be the [desired behavior](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/env-vars.md#comparison-table-with-current-behavior) based on the collector SIG's documentation.
