### ISSUE TITLE
profiles/follow up: location references in sample

### ISSUE THREAD

**Issue by florianl** [open-telemetry/opentelemetry-specification#4307]
This is a follow up for https://github.com/open-telemetry/oteps/pull/239#discussion_r1497131334 around `message Sample` and its use of `location_index`, `locations_start_index` and `locations_length`:

https://github.com/open-telemetry/oteps/blob/dc619dfc70f174ef31caf90f14e8b00600da4049/text/profiles/0239-profiles-data-model.md?plain=1#L518-L527

As an example, consider the following stack in a folded format:
```
foo;bar;baz 100
abc;def 200
foo;bar 300
abc;ghi 400
foo;bar;qux 500
```
Like in most stack traces, the base frames are similar, but there is a variation in the leaf frames. To reflect this, the last two  traces use different leaf frames, `ghi` and `qux`.

Should the resulting sample look like the following?

```
sample:
  - locations_start_index: 0
    locations_length: 3
    value:
      - 100
  - locations_start_index: 3
    locations_length: 2
    value:
      - 200
  - locations_start_index: 0
    locations_length: 2
    value:
      - 300
  - locations_start_index: 5
    locations_length: 2
    value:
      - 400
  - locations_start_index: 7
    locations_length: 3
    value:
      - 500
location_indices:
  - 0 # foo
  - 1 # bar
  - 2 # baz
  - 3 # abc
  - 4 # def
  - 3 # abc 
  - 5 # ghi
  - 0 # foo
  - 1 # bar
  - 6 # qux
location:
  - line:
      - function_index: 0 # foo
  - line:
      - function_index: 1 # bar
  - line:
      - function_index: 2 # baz
  - line:
      - function_index: 3 # abc
  - line:
      - function_index: 4 # def
  - line:
      - function_index: 5 # ghi
   - line:
      - function_index: 6 # qux
function:
  - name: 1 # foo
  - name: 2 # bar
  - name: 3 # baz
  - name: 4 # abc
  - name: 5 # def
  - name: 6 # ghi
  - name: 7 # qux
  ```

In particular for deep stack traces with a high number of similar frames and where only leaf frames are different, the use of `locations_start_index`, `locations_length` with `location_indices` will get more complex than the (deprecated) `location_index` which just holds a list of IDs into the location table.

The original [pprof message Sample](https://github.com/google/pprof/blob/fb44976bdcd59b48559fb1763d69313508ad3a75/proto/profile.proto#L104-L128) does also not use the `_start_index` / `_length` approach. From my understanding all messages of type `Sample` within the same `Profile` groups stack traces from the same origin/with the same attributes.
For a different set of attributes, I think, a dedicated `Profile` should be preferred with its own attributes.

An alternative, to allow sharing `Mapping`, `Location` and `Function` information between stack traces with different attributes would be to move these three tables one layer up into `ProfileContainer`, so that they can be referenced from each `Profile`.

While the variety of leaf frames is usually high and attributes are often more static, can we remove the `deprecated` label from `location_index` in `message Sample` and let the user either set `location_index` or `location_start_index` with `locations_length`?
